name: Build llama.cpp for Android ARM64

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-android:
    runs-on: ubuntu-latest

    env:
      ANDROID_NDK_VERSION: 25.1.8937393
      ANDROID_API_LEVEL: 24
      ANDROID_ABI: arm64-v8a

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3
        with:
          api-level: ${{ env.ANDROID_API_LEVEL }}
          build-tools-version: 33.0.2

      - name: Install Android NDK
        run: |
          sdkmanager --install "ndk;${ANDROID_NDK_VERSION}"
          echo "ANDROID_NDK_HOME=$ANDROID_SDK_ROOT/ndk/${ANDROID_NDK_VERSION}" >> $GITHUB_ENV

      - name: Cache Android NDK
        uses: actions/cache@v3
        with:
          path: ${{ env.ANDROID_NDK_HOME }}
          key: ${{ runner.os }}-android-ndk-${{ env.ANDROID_NDK_VERSION }}
          restore-keys: |
            ${{ runner.os }}-android-ndk-

      - name: Configure CMake for Android
        run: |
          mkdir -p build-android
          cd build-android

          cmake \
            -DCMAKE_TOOLCHAIN_FILE=$ANDROID_NDK_HOME/build/cmake/android.toolchain.cmake \
            -DANDROID_ABI=$ANDROID_ABI \
            -DANDROID_NATIVE_API_LEVEL=$ANDROID_API_LEVEL \
            -DCMAKE_BUILD_TYPE=Release \
            -GGML_CUDA=ON \
            ..

      - name: Build libllama.so
        run: |
          cd build-android
          cmake --build . --config Release -- -j$(nproc)

      - name: Upload libllama.so artifact
        uses: actions/upload-artifact@v4
        with:
          name: libllama-android-arm64
          path: build-android/bin/libllama.so
          retention-days: 30
